In [87]:
import datetime
import pytz
import pandas as pd

In [88]:
concerts = pd.read_csv("tz_list.csv")

In [89]:
concerts

,City,UTC,IANA,ShowTime
0,Costa Rica,UTC-06:00,America/Costa_Rica,2022-03-18 15:00:00
1,Dominican Republic,UTC-04:00,America/Santo_Domingo,2022-03-22 15:00:00
2,Mexico,UTC-05:00,America/Mexico_City,2022-03-25 15:00:00
3,US Los Angeles,UTC-08:00,America/Los_Angeles,2022-04-26 15:00:00
4,US Dallas,UTC-06:00,America/Chicago,2022-05-06 15:00:00
5,US Houston,UTC-06:00,America/Chicago,2022-05-08 15:00:00
6,US Phoenix,UTC-07:00,America/Phoenix,2022-05-12 15:00:00
7,US Santa Clara,UTC-08:00,America/Los_Angeles,2022-05-15 15:00:00
8,US Chicago,UTC-06:00,America/Chicago,2022-05-28 15:00:00
9,US Washington DC,UTC-05:00,America/New_York,2022-06-01 15:00:00
10,US East Rutherford,UTC-05:00,America/New_York,2022-06-04 15:00:00
11,US Philadelphia,UTC-05:00,America/New_York,2022-06-08 15:00:00
12,US Atlanta,UTC-05:00,America/New_York,2022-06-11 15:00:00
13,US Tampa,UTC-05:00,America/New_York,2022-06-14 15:00:00
14,Frankfurt Am Main,UTC+01:00,Europe/Berlin,2022-07-02 15:00:00
15,Warsaw,UTC+01:00,Europe/Warsaw,2022-07-08 15:00:00
16,Berlin,UTC+01:00,Europe/Berlin,2022-07-10 15:00:00
17,Paris,UTC+01:00,Europe/Paris,2022-07-16 15:00:00
18,Brussels,UTC+01:00,Europe/Brussels,2022-05-08 15:00:00
19,London,UTC+0,Europe/London,2022-08-12 15:00:00
20,Glasgow,UTC+0,Europe/London,2022-08-23 15:00:00
21,Rio de Janerio,UTC-03:00,America/Sao_Paulo,2022-09-10 15:00:00
22,Bogota,UTC-05:00,America/Bogota,2022-09-17 15:00:00
23,Lima,UTC-05:00,America/Lima,2022-09-20 15:00:00
24,Santiago,UTC-03:00,America/Santiago,2022-09-23 15:00:00
25,Buenos Aires,UTC-03:00,America/Argentina/Buenos_Aires,2022-10-25 15:00:00

In [90]:
for row in concerts.iterrows():
    czone = timezone(row[1]["IANA"])
    lzone = timezone('Asia/Kolkata')
    ctime = czone.localize(datetime.datetime.fromisoformat(row[1]["ShowTime"]))
    ltime = lzone.localize(datetime.datetime.now())
    diff = ctime - ltime
    print(row[1]["City"],diff)

14 days, 8:12:43.050930
18 days, 6:12:43.049716
21 days, 8:12:43.049203
53 days, 9:12:43.048844
63 days, 7:12:43.048347
65 days, 7:12:43.048106
69 days, 9:12:43.047907
72 days, 9:12:43.047729
85 days, 7:12:43.047565
89 days, 6:12:43.047400
92 days, 6:12:43.047241
96 days, 6:12:43.047085
99 days, 6:12:43.046935
102 days, 6:12:43.046523
120 days, 0:12:43.046314
126 days, 0:12:43.046132
128 days, 0:12:43.045961
134 days, 0:12:43.045749
65 days, 0:12:43.045503
161 days, 1:12:43.045345
172 days, 1:12:43.045210
190 days, 5:12:43.045069
197 days, 7:12:43.044887
200 days, 7:12:43.044753
203 days, 5:12:43.044622
235 days, 5:12:43.044492